jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run make
        run: make
      - name: List files
        run: dir
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./srtla_rec.exe
            ./srtla_send.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
